# Site settings
client:
title: Kettle
email: dev@ocupop.com
url: "http://ourkettle.com"
permalink: pretty

# Social sharing
description:
socialshare:
  featured_image:
  twitter:
    username:
    image:

# Google Analytics
analytics_code: UA-106357720-15


# Collections
collections:
  examples:
    output: true
    permalink: /examples/:path/

defaults:
  -
    scope:
      type: 'examples'
    values:
      layout: example
      # variable_name: value

# Build settings
safe: false
sass:
  # style: compressed
  sass_dir: _scss
plugins:
  - jekyll-sitemap

placeholder_image: https://via.placeholder.com/1000x1000/333333/000000?text=Placeholder

